[package]
name = "aoc-2b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.29.0"
regex = "1.5.4"
lazy_static = "1.4.0"
num-traits = "0.2.14"
